import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import GrainyFilter from "@/components/grainy-filter";
// import { AiModeProvider } from "@/contexts/ai-mode-context";
// import { AiModeController } from "@/components/ai-mode-controller";
import ThemeToggleButton from "@/components/theme-toggle-button";

const spaceGrotesk = Space_Grotesk({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased bg-zinc-50 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <GrainyFilter />
          {/* <AiModeProvider> */}
          <div className="fixed top-5 right-5 z-2 flex items-center gap-3">
            {/* <AiModeController /> */}
            <ThemeToggleButton />
          </div>
          {children}
          {/* </AiModeProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
